### ISSUE TITLE
Point to r4ss DoProjectPlots

### ISSUE THREAD

**Issue by brianlangseth-NOAA** [pfmc-assessments/rebuilder#2]
@kellijohnson-NOAA I think its cleaner to remove the do_project_plots.R file in the R folder and instead point to r4ss::DoProjectPlots, which is going to be updated more frequently. If I remove do_project_plots.R from the R folder, will the corresponding material in man be automatically removed?

**Comment by kellijohnson-NOAA** [comment]
It will, after you run `devtools::document()`.

**Comment by iantaylor-NOAA** [comment]
But wait, if do_project_plots() is available in this package, why not just delete from r4ss instead?
The "updated more frequently" assumption depends entirely on who is going to be doing the updating, which might just be whoever is doing rebuilding analyses (e.g. @brianlangseth-NOAA).

**Comment by brianlangseth-NOAA** [comment]
I was thinking general package maintenance as opposed to function maintenance. I can update the function in either place. My other logic was that r4rss has a broader audience than pfmc-assessments. Most people are going to have r4ss loaded so one less step in getting material for rebuilding plots. I understand your thoughts @iantaylor-NOAA but still seems like r4ss is a more sensible location.

@chantelwetzel-noaa as the original creator of the do_project_plots function in rebuilder, do you have a preference?

**Comment by chantelwetzel-noaa** [comment]
Whenever possible I think we should reduce redundancy to make our lives easier.  It has been a couple of years so I don't remember all the details well but I think the ` do_project_plots` used much of the same code from the r4ss::DoProjectPlots but then added some specific plotting I wanted.  I think only one version of this code should be maintained and in my mind, it makes sense for that function to live in the rebuilder repo.  There is a very small number of people who will be interested in this functionality (West Coast groundfish and cps assessors). Plus, I don't think these functions depend upon other functionality in r4ss (not using SS3 model output object created by r4ss::SS_output).

**Comment by brianlangseth-NOAA** [comment]
The codes are the same except for the names of the function, and the use of seq_along instead of 1:length(years) per commit r4ss/r4ss@66f7658 and some added commented out code within the r4ss version

**Comment by brianlangseth-NOAA** [comment]
@iantaylor-NOAA The above pull request (#3) moved RebuildPlots.R and its history into this repository. Handle that file within r4ss however you see fit. Closing this issue
